# Generated by Django 4.1.7 on 2023-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumer',
            old_name='skilss',
            new_name='skills',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_costumer',
            field=models.BooleanField(default=True),
        ),
    ]
