# Generated by Django 4.1.7 on 2023-04-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_skilss_costumer_skills_alter_user_is_costumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_costumer',
            field=models.BooleanField(default=False),
        ),
    ]
