# Generated by Django 4.1.7 on 2023-04-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_costumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pemilikkos',
            old_name='kos_name',
            new_name='pemilikkos_name',
        ),
    ]
