# Generated by Django 4.1.7 on 2023-04-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_kos_name_pemilikkos_pemilikkos_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pemilikkos',
            old_name='pemilikkos_name',
            new_name='agency_name',
        ),
        migrations.RenameField(
            model_name='pemilikkos',
            old_name='description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='pemilikkos',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pemilikkos',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/%Y/%m/%d/'),
        ),
    ]
