# Generated by Django 4.1.7 on 2023-04-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_pemilikkos_name_pemilikkos_agency_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumer',
            old_name='phone',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='portofolio',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='skills',
        ),
        migrations.AddField(
            model_name='costumer',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='pemilikkos',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
