# Generated by Django 4.1.3 on 2023-02-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_poi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='area',
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Kost', 'Kost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rental_frequency',
            field=models.CharField(blank=True, choices=[('year', 'year'), ('Month', 'Month'), ('Week', 'Week'), ('Day', 'Day')], max_length=20, null=True),
        ),
    ]
