# Generated by Django 4.1.3 on 2023-02-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_listing_area_alter_listing_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='id_listing',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
