# Generated by Django 4.1.3 on 2023-02-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_listing_id_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='borough',
        ),
    ]
