# Generated by Django 4.1.7 on 2023-04-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_alamat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='seller',
            new_name='user',
        ),
    ]
