# Generated by Django 4.1.7 on 2023-04-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_rename_seller_listing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='transaksi',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionDetail',
        ),
    ]
