# Generated by Django 4.1.7 on 2023-04-19 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0014_remove_transactiondetail_listing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_transaksi', models.IntegerField(blank=True, null=True)),
                ('status_transaksi', models.CharField(blank=True, max_length=11, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('barang_dipesan', models.BooleanField(default=False)),
                ('barang_dibeli', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='listings.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
