# Generated by Django 4.1.7 on 2023-04-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_transaksi',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fullName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rentalFrequency',
            field=models.CharField(blank=True, choices=[('year', 'year'), ('Month', 'Month'), ('Week', 'Week'), ('Day', 'Day')], max_length=20, null=True),
        ),
    ]
