# Generated by Django 4.1.7 on 2023-04-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_remove_transaction_total_transaksi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status_transaksi',
        ),
    ]
