# Generated by Django 4.1.7 on 2023-04-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_costumer_address_alter_pemilikkos_address'),
        ('listings', '0017_remove_transaction_status_transaksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.costumer'),
        ),
    ]
