# Generated by Django 4.1.7 on 2023-04-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_transaction_user_alter_transaction_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status_transaksi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
