# Generated by Django 4.1.7 on 2023-04-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_transaction_status_transaksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status_transaksi',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='barang_dibeli',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
