# Generated by Django 4.1.7 on 2023-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_remove_transaction_status_transaksi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='barang_dibeli',
            field=models.BooleanField(null=True),
        ),
    ]
