# Generated by Django 4.1.7 on 2023-04-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_alter_transaction_barang_dibeli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='barang_dibeli',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
