# Generated by Django 4.1.7 on 2023-04-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_transaction_buktitransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
