# Generated by Django 4.1.7 on 2023-04-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_listing_available_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='available_room',
        ),
    ]
