# Generated by Django 4.1.7 on 2023-04-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_alter_listing_listing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.AddField(
            model_name='listing',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_per_year',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rental_frequency',
            field=models.CharField(blank=True, choices=[('Year', 'Year'), ('Month', 'Month'), ('Day', 'Day')], max_length=20, null=True),
        ),
    ]
