# Generated by Django 4.1.7 on 2023-04-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_remove_listing_price_listing_price_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='rental_frequency',
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture1',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture2',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture3',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture4',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture5',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
