# Generated by Django 4.1.7 on 2023-04-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_remove_listing_rental_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='alamat',
            new_name='address',
        ),
    ]
