# Generated by Django 4.1.7 on 2023-04-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_rename_alamat_listing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_status',
            field=models.CharField(blank=True, choices=[('Rental', 'Rental')], max_length=20, null=True),
        ),
    ]
