# Generated by Django 4.1.7 on 2023-04-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_alter_listing_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rentalFrequency',
            field=models.CharField(blank=True, choices=[('Year', 'Year'), ('Month', 'Month'), ('Day', 'Day')], max_length=20, null=True),
        ),
    ]
