# Generated by Django 4.2 on 2023-05-31 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_alter_listing_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='user',
        ),
    ]
